### ISSUE TITLE
window is not defined in manifest.js

### ISSUE THREAD

**Issue by Floridus** [talk2MeGooseman/react-twitch-embed-video#1]
Hello author,

When I ran my server.js file I got an error from your module.

```
node_modules\react-twitch-embed-video\dist\manifest.js:1

ReferenceError: window is not defined```

I may have found a solution for you. Maybe the module "window-or-global" will help?

Thank you.

**Comment by talk2MeGooseman** [comment]
Sorry for late response, very late in fact. This is a wrapper around the Twitch player which only handles rendering inside a browser DOM. The believe that might be the root of your issue.
