### ISSUE TITLE
Autoplay false not working

### ISSUE THREAD

**Issue by this-is-rafa** [talk2MeGooseman/react-twitch-embed-video#117]
I've got `autoplay={false}` set, but whenever the component is loaded, it starts playing automatically. This in turn also fires the `onVideoPlay` callback. This also happens on the example page.

I saw that this was an issue in the past, but it was closed. Is this just something we can expect not to work in the foreseeable future?

Thanks for the plugin.

v1.1.4 Safari/Chrome/Firefox.

**Comment by talk2MeGooseman** [comment]
Ill take a look at this again. There was an issue with having the Twitch honoring the flag so I tried programitcally solving the issue but maybe there is some conditions that were not met.

**Comment by talk2MeGooseman** [comment]
New major update release for the extension, version 2. Some breaking changes were made to the code but I think I fixed the bug with the autoplay. Take a look at the updated docs and let me know of things work.
