### ISSUE TITLE
Request: iFrame should be unmounted after update.

### ISSUE THREAD

**Issue by Jarivdberg** [talk2MeGooseman/react-twitch-embed-video#16]
Hello,

As talked about on stream. 

Make it dynamic so that the channel will change upon this.setState channel change. And not re-add another iFrame.

**Comment by talk2MeGooseman** [comment]
Tried to replicate the issue but couldn't, let me know if you run across this again and if possible with a little demo on codesandbox.io replicating it. It will help a lot. Closing, for now, we can reopen it again later
