### ISSUE TITLE
iFrame refresh

### ISSUE THREAD

**Issue by RgtArRr** [talk2MeGooseman/react-twitch-embed-video#164]
Even if I hardcoded the channel name without any other props, every some state values changes the iFrame refresh itself.

**Comment by talk2MeGooseman** [comment]
Thanks for filing an issue. Do you have any example code for what you are experiencing so I can reproduce the issue?

**Comment by talk2MeGooseman** [comment]
Going to close this for now. Most of the time if your state values are changing the iFrame in refreshing you might need to double-check how you're setting the passed props. It might think you're sending it new data when you actually now.

**Comment by RgtArRr** [comment]
Sorry, I forgot to check the notifications.

Here's a basic example, every time I click on the button, the iframe refresh even with the channel name hardcoded

```
export default class Test extends React.Component {
    constructor (props) {
        super(props);
        this.state = {value: 0};
    }

    componentDidMount () {
    }

    onClick = (data) => {
        this.setState({value: Math.random()});
    };

    render () {
        return (
            <div className={'row'}>
                <div className={'col-md-3'}>
                    <div className="page-header mc">
                        {this.state.value}
                    </div>
                    <div className="list-group sidebar">
                        <button onClick={this.onClick}>Click me</button>
                    </div>
                </div>
                <div className={'col-md-9  col-md-offset-3 text-center'}>
                    <ReactTwitchEmbedVideo channel="talk2megooseman"/>
                </div>
            </div>
        );
    }
}
```

**Comment by talk2MeGooseman** [comment]
Thanks for the code, I am able to reproduce it like you said, Ill be working on some refactoring of how I am handling the proper to fix this, stay tuned!

**Comment by crlucasdias** [comment]
I had the same issue
not sure if thats the best solution, but u can use React Memo

function Twitch(props) {
        return (
        <div>
            <ReactTwitchEmbedVideo  channel={props.video}/>
        </div>
    )
}
export default React.memo(Twitch)

**Comment by talk2MeGooseman** [comment]
Deployed fix for the constant re-rendering, like @crlucasdias mentioned. The solution on my end was just to use `React.memo` to avoid rendering the component if the props haven't changed.

**Comment by talk2MeGooseman** [comment]
You can find the change on version 2.0.4
