### ISSUE TITLE
Storybook doesnt work

### ISSUE THREAD

**Issue by imagitama** [talk2MeGooseman/react-twitch-embed-video#171]
## Issue

Storybook demos are blank:

![image](https://user-images.githubusercontent.com/1967342/86525272-a84afa00-beb7-11ea-9877-47236041b71a.png)

Console:

![image](https://user-images.githubusercontent.com/1967342/86525278-b4cf5280-beb7-11ea-8401-9cbf7ca700ff.png)

Brave browser 
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by imagitama** [comment]
Nevermind turns out my browser blocks 3rd party cookies by default which causes the error:

![image](https://user-images.githubusercontent.com/1967342/86525724-7f2d6800-bebd-11ea-98f8-0042964ac9b8.png)

Maybe something in the docs to help people like me in future would be good

**Comment by talk2MeGooseman** [comment]
If you're using a browser like Brave that will do the trick, it will be a common problem with a lot of fo embeds

**Comment by talk2MeGooseman** [comment]
Added small thing in README
