### ISSUE TITLE
Embed not working in mobile Chrome

### ISSUE THREAD

**Issue by amandala** [talk2MeGooseman/react-twitch-embed-video#180]
I have implemented the package and it works great in all desktop browsers, however, most of the time it give the following error **"The video is either unavailable or not supported in this browser (Error #400)"** in mobile Chrome on both tablets and phones. I have attached a screenshot of one of the websites I am using this on. [www.impactfestival.ca](www.impactfestival.ca) Mobile Safari and Firefox work fine on my iPad.

I looked into the error code and it seems to be a CORS issue related to the parent attribute on the iframe. I have added a parent property for the domain that the embed is hosted on, but I still see this issue. Any ideas?

For reference, this is my component implementation 

```
import React from "react";
// @ts-ignore
import ReactTwitchEmbedVideo from "react-twitch-embed-video";

import styles from "./index.module.scss";

const TwitchChannel = ({ channel }: { channel: string }) => {
  const [showChat, setShowChat] = React.useState(false);

  return (
    <div>
      <div className={styles.StreamControls}>
        <button
          className={styles.ChatButton}
          onClick={() => setShowChat(!showChat)}
        >
          {showChat ? "Hide" : "Show"} Chat
        </button>
      </div>
      <ReactTwitchEmbedVideo
        layout={showChat ? "video-with-chat" : "video"}
        chat={window.innerWidth > 1025 ? "default" : "mobile"}
        theme="dark"
        width="100%"
        height={window.innerWidth > 1025 || showChat ? "900px" : "300px"}
        channel={channel}
        parent={["impactfestival.ca"]}
      />
    </div>
  );
};

export default TwitchChannel;
```
![IMG_0010](https://user-images.githubusercontent.com/6064242/89677055-f170de00-d8a9-11ea-8b56-83a672987276.PNG)

**Comment by amandala** [comment]
This seems to be an issue with the stream itself. Unsure if it's when we are offline, or if there stream is corrupted somehow for mobile chrome, but a live channel works fine. Perhaps not an issue with this package, but I am curious if anyone else landing here has found this issue.

**Comment by talk2MeGooseman** [comment]
I haven seen any reports on this issue but its worth keeping this open to see if other reports come in, might be something to report to the Twitch Dev team if more poeple see the issue.
