### ISSUE TITLE
The video works but I get spammed with errors.

### ISSUE THREAD

**Issue by Stallind** [talk2MeGooseman/react-twitch-embed-video#19]
Here's a courple of the errors I'm receiving. 

https://gyazo.com/d352003062cbd5c80ac200e2c1ad1e88

https://gyazo.com/380c0587ab153f2ecc8aba60dcab7a4d

**Comment by talk2MeGooseman** [comment]
Hey @Stallind for filing an issue. This is a known issue with just the Twitch JS lib that used in the iFrame in general. Nothing we can have direct control over. It annoying but it works!

**Comment by Stallind** [comment]
Thanks for fast reply, have a nice day
