### ISSUE TITLE
Set width and height of video

### ISSUE THREAD

**Issue by cindy100295** [talk2MeGooseman/react-twitch-embed-video#20]
How to set width and height to 100% to `<div id="xx">` instread of `<iframe>`? 
Here is my code and the interface: 
```
case 'twitchChannel':
        return <TwitchEmbedVideo
          height="100%" width="100%"
          channel={this.parseTwitchChannel(url)} layout="video"
          targetClass = {index.toString()}
          />
      case 'twitchVideo':
        return <TwitchEmbedVideo
          height="240" width="400"
          video={this.parseTwitchVideo(url)} 
          targetClass = {index.toString()}
          />
```
![image](https://user-images.githubusercontent.com/11485812/66538172-3e045500-eaf1-11e9-9ea2-13ce8b225823.png)
The left is set as `height="240" width="400"`, the right one is set as `height="100%" width="100%"` but it does not work because 100% is not set to the `<div>` outside `<iframe>`. 
Is there any way to do it? Thanks! 

I think it could be fixed if it can set `targetClass` as class instead of id.

**Comment by talk2MeGooseman** [comment]
Thanks for filing and issue! Ill try to come up with a code example for you to better help.

**Comment by talk2MeGooseman** [comment]
@cindy100295 Hey took some time to look at this issue. Ill try working on a good solution for this if you want to inline the styles for parent container. You do have the option of creating a CSS selector that targets the `targetClass` for your Embed and set the width and height that way. 
This is actually better practice then inlining the styles as part of the component props since its easier to maintain.
Let me know if this helps!
![](https://render.bitstrips.com/v2/cpanel/4f211e34-f0a8-4ad4-b294-4aadf9aa76b7-7bce6184-0c67-4209-b976-bec06e1848e6-v1.png?transparent=1&palette=1)

**Comment by cindy100295** [comment]
Hi thanks for the reply. The issue here is that `targetClass` is not creating a **class** but an **id**. 
![image](https://user-images.githubusercontent.com/11485812/66628580-4205a500-ebcd-11e9-9e90-daaa8345c36a.png)
My code is: 
```
case 'twitchChannel':
                return <TwitchEmbedVideo
                    height="100%" width="100%"
                    channel={this.parseTwitchChannel(url)} layout="video"
                    targetClass={`twitch-` + index.toString()}
                />
```
Not sure it is a bug? 
My current solution is to hard code a bunch of style for these ids in CSS. 
```
#twitch-0, #twitch-1, #twitch-2, #twitch-3, #twitch-4, #twitch-5, #twitch-6, #twitch-7, #twitch-8 {
    width: 100%;
    height: 100%;
}
```

**Comment by talk2MeGooseman** [comment]
@cindy100295 Version 1.1.2 is out that addresses this issue, there was some delay in getting the release actually on NPM with changes to Github Actions. Tested the solution in this example sandbox https://codesandbox.io/s/test-video-embed-bug-ijjk2. If you update, it should just work now. Thanks for filing the issue.

**Comment by segersniels** [comment]
I'm encountering issues with setting `height` to 100%. It works if the parent element is not the entire screen. For some reason when I try to use both width and height as 100% the height player gets super thin in height. It's fixed though by setting `position: absolute` on the top most iframe.

**Comment by talk2MeGooseman** [comment]
Wow, talk about a crappy corner case. Can you whip up an example of the issue? If it's not easily fixable I might add a part in the readme calling this out and the workaround. Thanks for the heads up @segersniels .

**Comment by segersniels** [comment]
Well not entirely sure if it's an issue on their end but currently solved by putting a `position: absolute` div around it, which kind of does the same thing and which made it actually go full height.
