### ISSUE TITLE
not work with typescript

### ISSUE THREAD

**Issue by anthowm** [talk2MeGooseman/react-twitch-embed-video#274]
I got an issue with typescript

```
Could not find a declaration file for module 'react-twitch-embed-video'. '/Users/anthonywillis/Documents/GitHub/latineo-react-web/node_modules/react-twitch-embed-video/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-twitch-embed-video` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-twitch-embed-video';`ts(7016)
```

**Comment by rodrigograca31** [comment]
Same problem here!
@anthowm have you found a solution!? 🤔🤔

**Comment by talk2MeGooseman** [comment]
I tried to eyeball the issue really quick but didn't find a quick solution, I am pretty sure I need to get webpack configured properly to get it to work with typescripts project importing the library. I am elbow deep in another open source project right now, once I am done there Ill see if I can fix the issue.

**Comment by rodrigograca31** [comment]
I did find 1 solution: 

change to an import:
```js
// import * as yourModuleName from 'module-name';
const yourModuleName = require('module-name');
```
or add
```js
// @ts-ignore
```

**Comment by talk2MeGooseman** [comment]
Finally got around to generating the declaration files and including them in the source. Now everything is all well in the multi-verse
