### ISSUE TITLE
Is it possible to style/move the chat box away from the video player?

### ISSUE THREAD

**Issue by CodyBontecou** [talk2MeGooseman/react-twitch-embed-video#376]
I'd like a bit more freedom in the look of my application. Is it possible/easily configurable to move the chat box away from the video player?

**Comment by talk2MeGooseman** [comment]
Unfortunately no, the look and feel of the video player are 100% dictated by the Twitch JS Player configs. You can only decide if you want to show or hide the chatbox. 

What you can possibly do is add the video player, choose to hide the chat window. Then embed the chat separately using the iframe embed. You can see how here https://dev.twitch.tv/docs/embed/chat.

That will give you the most customization.

**Comment by CodyBontecou** [comment]
Dang, okay. That makes sense.
