### ISSUE TITLE
Duplicated players of the same stream

### ISSUE THREAD

**Issue by slicycode** [talk2MeGooseman/react-twitch-embed-video#389]
Hi !
I've tried to use your package with Reactjs, but the player seems to duplicate ( two iframes are generated when there's only one "ReactTwitchEmbedVideo" component ). There was an older issue that had been closed but I couldn't find any solution.<br />
![2022-07-23 18_09_05-Window](https://user-images.githubusercontent.com/60575576/180613262-129a3595-f707-4009-8f0b-d51a529d7507.png)

![2022-07-23 18_09_32-Window](https://user-images.githubusercontent.com/60575576/180613265-85be5c53-401c-41e3-82d5-d6870d07aa20.png)

Here's my code : 

(App.js)
```
import ReactTwitchEmbedVideo from "react-twitch-embed-video"

const App = () => {
  return (
    <div>
      <ReactTwitchEmbedVideo channel='xqc' />
    </div>
  )
}

export default App
```

(index.js)
```
import React from "react"
import ReactDOM from "react-dom/client"
import "./index.css"
import App from "./App"

const root = ReactDOM.createRoot(document.getElementById("root"))
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)

```

**Comment by talk2MeGooseman** [comment]
Thanks for the issue and also thank you for some example code. I will take a look at this when I get back from my convention.

**Comment by RichieRichCR** [comment]
Hi there, I am having the same issue, did you come across a solution?

**Comment by talk2MeGooseman** [comment]
> Hi there, I am having the same issue, did you come across a solution?

@RichieRichCR  This is a little bit of a tricky bug to track, is your code similar to the example above, if not could you provide an example so I can play it with and see what might work for your use case.

**Comment by RichieRichCR** [comment]
Hi @talk2MeGooseman, thanks for getting back to me... I was testing, so spun up a new Create Next App using npx, then added your package... Below is the code used... 

`import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const ReactTwitchEmbedVideo = dynamic(() => import('react-twitch-embed-video'), {
  ssr: false,
})

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ReactTwitchEmbedVideo channel="channel_name" />
      </main>

    </div>
  )
}
`

**Comment by talk2MeGooseman** [comment]
Got to fix this issue, weird issue with the script tag including twitch causing a chain reaction.
