### ISSUE TITLE
Twitch embed autoplay not working correctly

### ISSUE THREAD

**Issue by mitrakmt** [talk2MeGooseman/react-twitch-embed-video#4]
From multiple tests, it seems like autoplay={false} isn't working. You mentioned this is likely due to the twitch embed API changing. I'll take a look at this shortly as well and see if there's a quick fix I can put in

**Comment by mitrakmt** [comment]
Unrelated to the above, but also receiving a ton of errors in the console from this component.
<img width="562" alt="screen shot 2018-12-21 at 10 36 48 pm" src="https://user-images.githubusercontent.com/7841122/50370693-f0722800-0570-11e9-8660-0ae8857c850a.png">

**Comment by cuvelierm** [comment]
I noticed the autoplay issue as well, is there any follow up on this? or should we look into this ourselves and create a PR?

**Comment by talk2MeGooseman** [comment]
Taking a look at this now. Thanks for patience

**Comment by talk2MeGooseman** [comment]
Seems like something change on Twitch's side the JS library no longer accepts the autoplay options when initializing the class. Took a stab and patching this and should be included in the upcoming 1.1.0 release.

**Comment by talk2MeGooseman** [comment]
1.1.0 released, let me know if you still see issues with new stuff
