### ISSUE TITLE
Height & Width don't update after init

### ISSUE THREAD

**Issue by benjaminjs** [talk2MeGooseman/react-twitch-embed-video#66]
Trying to keep the embed bound to a container, but it looks like ignoring those props. 

Is there an issue if I added height and width updating?

**Comment by talk2MeGooseman** [comment]
Can you provide some example code so I can debug the issue, doubel check your on the latest version also :)

**Comment by benjaminjs** [comment]
https://codesandbox.io/s/quizzical-raman-jtc7c Here is a rough example.

**Comment by talk2MeGooseman** [comment]
Thanks for sample code. I think I know what the issue is and the fix. Ill play around with it tonight.

**Comment by benjaminjs** [comment]
Okie dokie. Well, let me know if I can help anyway

**Comment by talk2MeGooseman** [comment]
Got the fix in! When the resize happens, the embed must be destroyed and rebuilt so you will see the embed disappear during the resize and will come back when its finally has time to load the contents. Use version 1.1.4.... DO NOT USE 1.1.3.... That version is broken. But its done!
![bitmoji](https://render.bitstrips.com/v2/cpanel/a640399f-2837-485b-881e-3de373e8f801-7bce6184-0c67-4209-b976-bec06e1848e6-v1.png?transparent=1&palette=1&width=246)
